CREATE DATABASE IF NOT EXISTS shop;
USE shop;

CREATE TABLE T_USER
(
  F_ID BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  F_EMAIL VARCHAR(50),
  F_NAME VARCHAR(50),
  F_PASSWORD VARCHAR(50),
  F_ROLE_ID BIGINT(20),
  F_SURNAME VARCHAR(50)

);