CREATE DATABASE IF NOT EXISTS shop;
USE shop;

CREATE TABLE users
(
  USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(70),
  NAME VARCHAR(70),
  SURNAME VARCHAR(70),
  PASSWORD VARCHAR(20),
  ROLE_ID LONG
);

CREATE TABLE profiles
(
  PROFILE_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  COUNTRY VARCHAR(50),
  STREET VARCHAR(50),
  HOUSE VARCHAR(5),
  APARTMENT VARCHAR(5),
  TELEPHONE VARCHAR(20),
  USER_ID INT UNIQUE,
  CONSTRAINT user_prof_fk FOREIGN KEY (USER_ID) REFERENCES users(USER_ID)
);

CREATE TABLE news
(
  NEWS_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TITLE VARCHAR(255),
  CONTENT BLOB,
  CREATED DATETIME,
  USER_ID INT,
  CONSTRAINT user_news_fk FOREIGN KEY (USER_ID) REFERENCES users(USER_ID)
);

CREATE TABLE comments
(
  COMMENT_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CONTENT BLOB,
  CREATED DATETIME,
  USER_ID INT,
  NEWS_ID INT,
  CONSTRAINT user_comment_fk FOREIGN KEY (USER_ID) REFERENCES users(USER_ID),
  CONSTRAINT news_comment_fk FOREIGN KEY (NEWS_ID) REFERENCES news(NEWS_ID)
);
